import mongoose, { Document, Schema } from 'mongoose';

export interface ICharacterMetaStat {
    character_id: string;
    character_name: string;
    usage_count: number;
    win_count: number;
    win_rate: number;
    trend: 'rising' | 'falling' | 'stable';
    top_strategies: string[];
}

export interface IMatchupInsight {
    character_a: string;
    character_b: string;
    win_rate_a: number; // percentage 0-100
    dominant_strategy: string;
    sample_size: number;
}

export interface IMetaReport {
    report_id: string;
    game_id: string;
    period: 'weekly' | 'patch' | 'monthly';
    patch_version?: string;
    generated_at: Date;
    status: 'generating' | 'ready' | 'error';
    error_message?: string;

    // Core meta intelligence
    tier_list: ICharacterMetaStat[];
    trending_characters: { rising: string[]; falling: string[] };
    dominant_strategies: string[];
    matchup_insights: IMatchupInsight[];

    // Narrative summary generated by Gemini
    meta_summary: string;
    patch_impact_summary?: string;

    // Data quality
    source_scenario_count: number;
    source_video_count: number;

    created_at?: Date;
    updated_at?: Date;
}

export interface IMetaReportDocument extends IMetaReport, Document {
    _id: mongoose.Types.ObjectId;
}

const CharacterMetaStatSchema = new Schema<ICharacterMetaStat>({
    character_id: { type: String, required: true },
    character_name: { type: String, required: true },
    usage_count: { type: Number, default: 0 },
    win_count: { type: Number, default: 0 },
    win_rate: { type: Number, default: 0 },
    trend: { type: String, enum: ['rising', 'falling', 'stable'], default: 'stable' },
    top_strategies: [{ type: String }],
}, { _id: false });

const MatchupInsightSchema = new Schema<IMatchupInsight>({
    character_a: { type: String, required: true },
    character_b: { type: String, required: true },
    win_rate_a: { type: Number, required: true },
    dominant_strategy: { type: String, required: true },
    sample_size: { type: Number, default: 0 },
}, { _id: false });

const MetaReportSchema = new Schema<IMetaReportDocument>({
    report_id: { type: String, required: true, unique: true, index: true },
    game_id: { type: String, required: true, index: true },
    period: { type: String, enum: ['weekly', 'patch', 'monthly'], required: true },
    patch_version: { type: String },
    generated_at: { type: Date, required: true },
    status: { type: String, enum: ['generating', 'ready', 'error'], default: 'generating' },
    error_message: { type: String },

    tier_list: [CharacterMetaStatSchema],
    trending_characters: {
        rising: [{ type: String }],
        falling: [{ type: String }],
    },
    dominant_strategies: [{ type: String }],
    matchup_insights: [MatchupInsightSchema],

    meta_summary: { type: String, default: '' },
    patch_impact_summary: { type: String },

    source_scenario_count: { type: Number, default: 0 },
    source_video_count: { type: Number, default: 0 },
}, {
    timestamps: {
        createdAt: 'created_at',
        updatedAt: 'updated_at',
    },
});

// Index for fetching latest report per game
MetaReportSchema.index({ game_id: 1, generated_at: -1 });
MetaReportSchema.index({ game_id: 1, period: 1, generated_at: -1 });

export const MetaReport = mongoose.model<IMetaReportDocument>('MetaReport', MetaReportSchema);
